arb-dir: lib/resources/l10n
template-arb-file: intl_en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
untranslated-messages-file: untranslated_localizations.txt
