name: trinity_wizards
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.3.3+2
  get_it: ^7.6.7
  google_fonts: 6.1.0
  built_value: ^8.9.2
  built_collection: ^5.1.1
  chopper: ^7.3.0
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  meta: ^1.9.1
  flutter_mobx: ^2.2.1+1
  package_info: ^2.0.2
  logging: ^1.2.0
  flutter_conditional_rendering: ^2.1.0
  internet_connection_checker_plus: ^2.2.0
  webview_flutter: ^4.5.0
  webview_flutter_wkwebview: ^3.10.2
  mockito: ^5.4.2
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  build_runner: ^2.4.9
  built_value_generator: ^8.9.2
  chopper_generator: ^7.3.0
  mobx_codegen: ^2.6.1

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # assets:
    # - assets/icons/
    
